### ISSUE TITLE
v1.2.0 Tracking Issue

### ISSUE THREAD

**Issue by gthao313** [bottlerocket-os/bottlerocket-update-operator#479]
This is a _"living"_ issue used to track bug fixes and things landing in the next release point release of Brupop v1.2.0

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Brupop release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

---

### Release captains 🧑‍✈️ 

@gthao313 

### Targeting 🎯 

- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/350
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/351

### Maintenance 🔧 

- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/476
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/446
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/415
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/416
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/418
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/453
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/462
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/463

**Comment by gthao313** [comment]
The 1.2.0 is alive now.
