### ISSUE TITLE
Brupop 1.3.0 Tracking Issue🐢

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket-update-operator#508]
This is a _"living"_ issue used to track bug fixes and things landing in the next release point release of Brupop v1.3.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Brupop release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [**_anything is subject to change_**](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/CODE_OF_CONDUCT.md), _**this isn't a guarantee**_ anything will _actually_ land in a given release, and this tracking issue is not all encompassing.

---

### Targeting 🎯 

- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/496
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/503
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/504
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/505
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/506
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/513
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/507
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/511
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/512
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/514
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/517
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/524
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/issues/523

**Comment by cbgbt** [comment]
I'm currently planning to release this on Thursday, 8/17/2023

**Comment by cbgbt** [comment]
While doing some larger-scale tests, I ran into a few issues that I'd like to iron out, namely these:
- https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/524
- https://github.com/bottlerocket-os/bottlerocket-update-operator/issues/523

This means that the release date will likely need to move. I'll post an update when it's more clear.

**Comment by cbgbt** [comment]
Brupop 1.3.0 is live: https://github.com/bottlerocket-os/bottlerocket-update-operator/releases/tag/v1.3.0

You can update using the helm repository or the updated YAML manifest directly. Please see the README for installation instructions and feel free to open an issue if you have any issues or questions.
