### ISSUE TITLE
Brupop 1.4.0 Tracking Issue :rabbit2: 

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket-update-operator#632]
This is a _"living"_ issue used to track bug fixes and things landing in the next release point release of Brupop v1.4.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Brupop release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [**_anything is subject to change_**](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/CODE_OF_CONDUCT.md), _**this isn't a guarantee**_ anything will _actually_ land in a given release, and this tracking issue is not all encompassing.

---

### Targeting 🎯 

- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/631
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/539
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/559
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/560
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/567
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/572
- [x] https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/617

**Comment by cbgbt** [comment]
[Brupop 1.4.0 is live!](https://github.com/bottlerocket-os/bottlerocket-update-operator/releases/tag/v1.4.0)
